# Generated by Django 4.2.4 on 2024-01-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shipping_address',
        ),
    ]
