# Generated by Django 4.2.4 on 2024-01-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_personal_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='username',
            new_name='user',
        ),
    ]
